// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package types

type LoginReq struct {
	Username   string `json:"username"`
	Password   string `json:"password"`
	VerifyCode string `json:"verifyCode"`
}

type LoginResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
	Data Resp   `json:"data"`
}

type RegisterReq struct {
	Username   string `json:"username"`
	Password   string `json:"password"`
	VerifyCode string `json:"verifyCode"`
}

type RegisterResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type Resp struct {
	UserId   int64  `json:"userId"`
	Username string `json:"username"`
	Token    string `json:"token"`
	ExpireAt int64  `json:"expireAt"`
}
