// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	account "infni-backend/apps/api/internal/handler/account"
	"infni-backend/apps/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: account.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: account.RegisterHandler(serverCtx),
			},
		},
	)
}
